//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project3 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Project3Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Project3Settings1 defaultInstance = ((Project3Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Project3Settings1())));
        
        public static Project3Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is project 3 setting1")]
        public string Project3Setting1 {
            get {
                return ((string)(this["Project3Setting1"]));
            }
            set {
                this["Project3Setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("This is project 3 setting 2")]
        public string Project3Setting2 {
            get {
                return ((string)(this["Project3Setting2"]));
            }
            set {
                this["Project3Setting2"] = value;
            }
        }
    }
}
