//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project2 {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    public sealed partial class Project2Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Project2Settings1 defaultInstance = ((Project2Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Project2Settings1())));
        
        public static Project2Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Wow this is a nice setting")]
        public string Project2Setting1 {
            get {
                return ((string)(this["Project2Setting1"]));
            }
            set {
                this["Project2Setting1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Good one!")]
        public string Project2Setting2 {
            get {
                return ((string)(this["Project2Setting2"]));
            }
            set {
                this["Project2Setting2"] = value;
            }
        }
    }
}
